Standardization
bionode/bionode-sam pull request #6
Opened 2017-06-02 16:24 UTC by StuntsPT

Added CONTRIBUTING.md, standardized README.md, improved "Standard JS" conformance, bumped package versions, removed spammy notifications and removed unimplemented tests.

2017-08-23 13:52 UTC, bmpvieira requested changes
Just need to keep mocha in tests

2017-08-23 13:52 UTC, bmpvieira commented on package.json
> +    "test": "standard && dependency-check .",
Please keep mocha here after the other tests.

2017-08-25 22:08 UTC, StuntsPT commented
Added the `mocha` tests back. However, a new error shows up complaining there are no tests to perform...

2017-08-28 15:45 UTC, bmpvieira commented
Sorry, I didn't see that tests were still missing. I'll merge your changes anyway and someone can add tests later.

2017-08-28 15:45 UTC, bmpvieira approved these changes

2017-08-28 15:46 UTC, merged